### ISSUE TITLE
Production build fails with global SCSS files

### ISSUE THREAD

**Issue by peteorpeter** [Debens/gatsby-plugin-scss-typescript#1]
The production build fails when there are global SCSS files imported.

Minimal repo for reproducing: https://github.com/peteorpeter/gatsby-plugin-scss-typescript-test

The error:

>TypeError: Cannot read property 'split' of undefined
    at CssModule.nameForCondition (/Users/petejones/projects/livefront/gatsby-plugin-scss-typescript-test/node_modules/mini-css-extract-plugin/dist/index.js:77:39)

It's quite possible that this isn't a bug and the solution is to find the right `cssLoaderOptions` in `gatsby-config.js`, but I have not found a combination that works.

I have tried a variety of suggestions from https://github.com/webpack-contrib/mini-css-extract-plugin/issues/156 and elsewhere. 

---

To reproduce, clone [this repo](https://github.com/peteorpeter/gatsby-plugin-scss-typescript-test) and run:

```sh
yarn
yarn run build
# 💥 BOOM!
```

 The development build runs without error.  Commenting out the import of `global.scss` removes the error in the production build. 

--- 

Many thanks for developing this plugin!  Even if this (maybe) bug were never resolved I'd work around this to keep using typed SCSS modules.

**Comment by Debens** [comment]
Thanks for reporting, and thanks for providing a reproducible environment! <3

I'll have a dig over the weekend!

**Comment by Debens** [comment]
Take a look at using release [v4.0.0](https://github.com/Debens/gatsby-plugin-scss-typescript/releases/tag/4.0.0), but note there are some breaking changes.

**Comment by peteorpeter** [comment]
🎊 

Global SCSS is working great for me with `v4`.  Many thanks @Debens!
