### ISSUE TITLE
How to deal with a multitude of *.module.scss.d.ts files?

### ISSUE THREAD

**Issue by Cry0nicS** [Debens/gatsby-plugin-scss-typescript#10]
I have installed the plugin, converted my `*.scss` files to `*.module.scss` and imported them according to the README. Everything worked.

All went great, except that every time I run `npm start` the plugin generates a `*.module.scss.d.ts` for each `.module.scss` file.

I end up having a huge amount of files now, each component looking like
![image](https://user-images.githubusercontent.com/29982205/83977563-0c56be80-a90a-11ea-8715-0a61a8209877.png)
![image](https://user-images.githubusercontent.com/29982205/83977566-14aef980-a90a-11ea-83a8-07bfef61569a.png)

Is this normal? Am I supposed to commit these 100s of `*..module.scss.d.ts` files? Or should I ignore all of them?
It seems to me like something went wrong...

**Comment by Debens** [comment]
This is expected and is an effect of using [typescript-plugin-css-modules](https://github.com/mrmckeb/typescript-plugin-css-modules) under the surface.

This is a method to achieve complete type safety to ensure the imports match the declared scss. 

I would recommend these are commented into your repo and will update automatically when the gatsby server is running.

If you prefer to not have these files there are other scss gatsby plugins that don't perform this declaration file generation but is a core feature for this plugin.

**Comment by Cry0nicS** [comment]
Thanks!

I decided to keep using it and went with committing all these extra files, as you suggested.
