### ISSUE TITLE
Compatibility to node-sass 5

### ISSUE THREAD

**Issue by jens-duttke** [Debens/gatsby-plugin-scss-typescript#15]
`node-sass` v5.0.0 is out since the 27th of October.

The `gatsby-plugin-scss-typescript` shows the warning:
```
gatsby-plugin-scss-typescript@4.0.13 requires a peer of node-sass@^4.5.0 but none is installed. You must install peer dependencies yourself.
```

The build process fails with
```
undefined failed

Node Sass version 5.0.0 is incompatible with ^4.0.0.
```
I'm not sure if this plugin is the source of the issue, but even if not, would it be possible to get it updated to support `node-sass` 5.0.0?

**Comment by martin-braun** [comment]
I think [this](https://stackoverflow.com/questions/64625050/error-node-sass-version-5-0-0-is-incompatible-with-4-0-0) is the reason. [Also _LibSass_ is deprecated](https://sass-lang.com/blog/libsass-is-deprecated) and it's used by `node-sass`. 

The [official Sass plugin of Gatsby](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sass) isn't using `node-sass` anymore, it uses `sass` (_Dart Sass_) that is [recommended by the Sass core team](https://sass-lang.com/blog/libsass-is-deprecated).

I think this issue should not be addressed in favor of compatibility to _Dart Sass_, I think this is broken, too.

**Comment by Debens** [comment]
Yar, seems I've let some dependencies lapse without my noticing, hoping to get around to this soon. In the meantime please feel free to open a PR to resolve the issue

**Comment by Debens** [comment]
Closing in favour of the more active [issues 16](https://github.com/Debens/gatsby-plugin-scss-typescript/issues/16).
