### ISSUE TITLE
Dart Sass support? - Generating development JavaScript bundle failed, Expected "{"

### ISSUE THREAD

**Issue by martin-braun** [Debens/gatsby-plugin-scss-typescript#16]
I'm using the Gatsby starter with Wordpress (`npm init gatsby` and selecting Wordpress). I also installed `sass`, not `node-sass`, because _LibSass_ that is used by `node-sass` [has been deprecated](https://sass-lang.com/blog/libsass-is-deprecated).

When I run `gatsby develop` I get this error when it tries to create the definition files for the SCSS modules:

```
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


        text-align: center;


                                    ^
      Expected "{".
  ╷
2 │ var content = require("!!../../node_modules/typings-for-css-modules-loader/lib/index.js??ref--16-oneOf-0-1!../../node_modules
/postcss-loader/src/index.js??postcss-6!../../node_modules/resolve-url-loader/index.js!../../node_modules/sass-loader/dist/cjs.js
??ref--16-oneOf-0-4!./index.module.scss");
  │

                                         ^
  ╵
  stdin 2:296  root stylesheet
      in /Users/marty/Projects/PHOENIX-HUMAN-PRIME/php-mediathek/src/pages/index.module.scss (line 2, column 296)

File: src/pages/index.module.scss

failed Re-building development bundle - 0.190s
```

This is really unfortunate. Does this package support `sass` (_Dart Sass_)? If not, wouldn't it be right to make it work with it, since it's [recommend to use it by the Sass core team](https://sass-lang.com/blog/libsass-is-deprecated).

**Comment by Debens** [comment]
Thanks for bringing this up! This is the direction I've been wanting to go but not yet found the time to upgrade this myself.

It may yet be a little longer until I can remove the node-sass dependency, feel free to create a PR in the meantime if you need something done faster, otherwise I hope to get around to it soon.

**Comment by Debens** [comment]
I've given it a "fast as possible" attempt without actually confirming anything works to see if I can unblock you.

(New laptop and I don't have any true to life examples to test against so apologies for the cowboy coding)

For now, give this alpha a go and let me know how bad it doesn't work!

```sh
yarn add gatsby-plugin-scss-typescript@5.0.1-alpha-255.0
```

You can remove node-sass and replace it with sass now.

**Comment by martin-braun** [comment]
Hi @Debens,

thanks for addressing this issue so fast, but please, keep it calm. I found a work-around by using _typed-scss-modules_, but I would prefer your solution to avoid a secondary task in the background.

I tried with your alpha version, but the issue still remains. Please take your time to do it properly, it's all good on my end. :)

**Comment by Debens** [comment]
Thank you for being patient, the kindness is much appreciated.

I've managed to put a little extra time into this which also includes support of `css-loader >=1` as well as dropping `node-sass` in favour of `sass`.

This is a breaking change and will result in a difference of the declaration file format, but does give more control over the result, once I can finalise a release I'll add some release notes on the changes but ultimately it can be a drop-in replacement. There is a potential for causing changes to the casing of style names depending on your version of `css-loader`, new version moved the `namedExport ` option to the locals with `exportLocalsConvention`.

For now, the minimum required would be:

```sh
yarn remove node-sass ; yarn add sass gatsby-plugin-scss-typescript@alpha
``` 

I've pushed some additional changes to the release alpha channel that should hopefully support your use case. I've confirmed that my (very simple) [example repository](https://github.com/Debens/gatsby-plugin-typescript-scss-modules-example) is happy with the changes but it would be great to confirm this will resolve this for you.

If this isn't the case I'd ask that we put together an example repository highlighting the issue in a distilled form so I can better find the root cause.

**Comment by martin-braun** [comment]
@Debens Thanks mate, I tested the new alpha version and now the error is different: 

```
 ERROR #11321  PLUGIN

"gatsby-plugin-scss-typescript" threw an error while running the onCreateWebpackConfig lifecycle:

useCssModules.flatMap is not a function

  25 |     const css = useCss.concat(sassLoaders);
  26 |     const cssModules = useCssModules
> 27 |         .flatMap(loader => (isCssLoader(loader) ? [typeLoader, loader] : loader))
     |          ^
  28 |         .concat(sassLoaders);
  29 |     switch (stage) {
  30 |         case 'develop':

File: node_modules/gatsby-plugin-scss-typescript/gatsby-node.js:27:10



  TypeError: useCssModules.flatMap is not a function
  
  - gatsby-node.js:27 Object.onCreateWebpackConfig
    [php-mediathek]/[gatsby-plugin-scss-typescript]/gatsby-node.js:27:10
  
  - api-runner-node.js:469 runAPI
    [php-mediathek]/[gatsby]/src/utils/api-runner-node.js:469:22
  
  - api-runner-node.js:620 resolve
    [php-mediathek]/[gatsby]/src/utils/api-runner-node.js:620:13
  
  - debuggability.js:384 Promise._execute
    [php-mediathek]/[bluebird]/js/release/debuggability.js:384:9
  
  - promise.js:518 Promise._resolveFromExecutor
    [php-mediathek]/[bluebird]/js/release/promise.js:518:18
  
  - promise.js:103 new Promise
    [php-mediathek]/[bluebird]/js/release/promise.js:103:10
  
  - api-runner-node.js:618 plugin
    [php-mediathek]/[gatsby]/src/utils/api-runner-node.js:618:16
  
  - util.js:16 tryCatcher
    [php-mediathek]/[bluebird]/js/release/util.js:16:23
  
  - reduce.js:166 Object.gotValue
    [php-mediathek]/[bluebird]/js/release/reduce.js:166:18
  
  - reduce.js:155 Object.gotAccum
    [php-mediathek]/[bluebird]/js/release/reduce.js:155:25
  
  - util.js:16 Object.tryCatcher
    [php-mediathek]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:547 Promise._settlePromiseFromHandler
    [php-mediathek]/[bluebird]/js/release/promise.js:547:31
  
  - promise.js:604 Promise._settlePromise
    [php-mediathek]/[bluebird]/js/release/promise.js:604:18
  
  - promise.js:649 Promise._settlePromise0
    [php-mediathek]/[bluebird]/js/release/promise.js:649:10
  
  - promise.js:729 Promise._settlePromises
    [php-mediathek]/[bluebird]/js/release/promise.js:729:18
  
  - async.js:93 _drainQueueStep
    [php-mediathek]/[bluebird]/js/release/async.js:93:12
```

**Comment by Debens** [comment]
`flatMap` is a part of ES2019 which is supported from node 11, seems I've been making some assumptions about the working environment. 

Looks like it's time to add babel. In the meantime, I'll check out the starter and confirm what's going on. If you want to work around this you can upgrade your node version, the current LTS is node 14.

**Comment by martin-braun** [comment]
@Debens Thanks, I'm good. I just like to point out that [gatsby-source-wordpress-experimental](https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/404#event-4203159165) still has issues with LTS (v14) and stable LTS (v12) so I've chosen to downgrade to legacy LTS (v10).

However, I'm not sure it's worth the effort to make it compatible with v10, unless others report the same issues. It's an experimental package that has problems with newer node versions, nonetheless.

Again, I'm good having my alternative I mentioned before, it's not urgent and most likely will solve itself with time.

**Comment by Debens** [comment]
I've added support under the alpha channel for older versions of node.

**Comment by martin-braun** [comment]
Hi @Debens, right now I'm not working on the project I tried to use your plugin on. I will close this in assumption that this got fixed in your recent release. I will consider to install it on the next Gatsby project I'm working on and I will report back if I got issues with it.

So, I'm closing this for now, so it's off the table for you. Thank you for your work, I really appreciate it.
