### ISSUE TITLE
Love the plugin but no postcss config and autoprefixing

### ISSUE THREAD

**Issue by joelpierre** [Debens/gatsby-plugin-scss-typescript#2]
Love the plugin. But I could not get an autoprefixer "easily" working. So I had to scrap using it and do a global generic type function for .scss files.

Any chance you can add autoprefixing?

**Comment by Debens** [comment]
Thanks for reporting this, I've added a quick fix postcss loader under release (3.1.0)[https://github.com/Debens/gatsby-plugin-scss-typescript/releases/tag/3.1.0]. Let me know if this is enough for you. 

You can you `postCssLoaderOptions` for now in the options if required.

If not i'll give this a deeper dive when I get a sec.

**Comment by peteorpeter** [comment]
I was about to report this issue and was delighted to see there is already a fix released!  Many thanks!

**Comment by joelpierre** [comment]
Thanks so much for doing this so quick! I will test it out and let you know!

**Comment by lxsymington** [comment]
> Thanks for reporting this, I've added a quick fix postcss loader under release [3.1.0](https://github.com/Debens/gatsby-plugin-scss-typescript/releases/tag/3.1.0). Let me know if this is enough for you.
> 
> You can you `postCssLoaderOptions` for now in the options if required.
> 
> If not i'll give this a deeper dive using the gatsby given rule set rather than patching together my own when I get a sec.

@Debens this option seems no longer to exist (as of 4.0.0 by the looks of it). Thought I would check here first that this is a regression of sorts, rather than there being a new way of passing postcss config, before opening a new issue?
