### ISSUE TITLE
Sass file splitting?

### ISSUE THREAD

**Issue by mosesoak** [Debens/gatsby-plugin-scss-typescript#20]
Hi, I'm trying this extension out with the hope that when loading any given page, only the styles imported on that page would be included in the HTML. Currently I'm seeing all modules published to all pages.

If it doesn't reduce the size and complexity of the styles, I'm not sure I see a point to using it since the only benefit would be scoping, but that's just a syntactic sugar in the end if there's no real-world benefit to users.

This is probably lack of proper webpack configuration. Can you provide an example that shows how to get the styles to split? I tried your example webpack configs but they don't seem to do the trick.

Thanks!

**Comment by Debens** [comment]
Optimizations such as code splitting are more viewed as contextual behavior depending on the site in question and not a responsibility of the transpiler. 

There are some other plugins out there that would give you the desired splitting off the single CSS file output, take a look at  [gatsby-plugin-split-css](https://www.gatsbyjs.com/plugins/gatsby-plugin-split-css/). Hopefully, adding this to the end of you gatsby-config plugins list will fit your usecase.
