### ISSUE TITLE
CSS Modules Do Not Work in Production Build

### ISSUE THREAD

**Issue by thejamespower** [Debens/gatsby-plugin-scss-typescript#3]
CSS classnames are removed from the DOM in `build` (although they still appear in the React DOM). Everything works fine in `develop`. I'll work on a simple reproduction repo' if needed. :)

<img width="559" alt="Screenshot 2019-07-19 at 11 05 27" src="https://user-images.githubusercontent.com/7080202/61527778-2ac37b00-aa15-11e9-9408-2d63eb18b666.png">
<img width="202" alt="Screenshot 2019-07-19 at 11 05 34" src="https://user-images.githubusercontent.com/7080202/61527784-2d25d500-aa15-11e9-89b3-f8f49882cadf.png">

**Comment by Debens** [comment]
Thanks for reporting this, there seems to be issues with using SSR in conjunction with mini-css-extract-plugin and css modules. I'll have a deeper dive when I get a chance.

In the mean time please feel free to take a drive yourself and create a PR with anything you find.

**Comment by Debens** [comment]
Hey, sorry I didn't manage to get a chance to look over the weekend, but I have a fix for you. Just upgrade to [4.0.7](https://github.com/Debens/gatsby-plugin-scss-typescript/releases/tag/v4.0.7) and everything should be good.

If not, let me know!

**Comment by thejamespower** [comment]
Awesome! Thanks @Debens
