### ISSUE TITLE
Does nothing

### ISSUE THREAD

**Issue by nayots** [Debens/gatsby-plugin-scss-typescript#8]
This is not working at all ?

plugins: `gatsby-plugin-scss-typescript`, 
YES

package.json:
    "gatsby-plugin-scss-typescript": "^4.0.10",
    "node-sass": "^4.13.1", 
YES

import * as styles from "./layout.module.scss"; Nothing happens
erros: Cannot find module './layout.module.scss'.
No .d.ts files are being generated.

**Comment by Debens** [comment]
@nayots - do you have more information, specfically an exmaple repo?

Please make sure you've added the plugin to your gatsby config.

**Comment by leepowelldev** [comment]
Getting a similar problem, and I've tried multiple other plugins too - no typings seem to get generated into the project. Not sure if Gatsby have changed something recently to cause these plugins all to stop working.

1. installed plugin as instructions
2. added to gatsby-config.js as instructions
3. `npm start`
4. application starts but cannot see any new *.d.ts files

**Comment by Debens** [comment]
Hmm... I'm not seeing the issue you are describing.

I've created an example repo for you to reproduce what you are describing so I can debug this for you.

https://github.com/Debens/gatsby-plugin-typescript-scss-modules-example

This was created through the gatsby-cli, which you can install through yarn/npm or brew

```sh
brew install gatsby-cli
// or
yarn global add gatsby

gatsby new gatsby-plugin-typescript-scss-modules-example
```

Then I only added the required packages 

```sh
yarn add gatsby-plugin-typescript gatsby-plugin-scss-typescript node-sass
```

I then replaced the pages with a simple component with its scss stylesheet. Finally by running `gatsby develop` you should see the declaration files being created. 

Note that these declaration files are a development aid and won't be generated in production, i.e. `gatsby build`.

**Comment by Erythros** [comment]
Running into the same issue as the guys above. In an existing project, where I used some .scss styling (without the `module`) I installed the plugin, yet nothing happens.
More over, now I'm getting a bunch of weird errors like
```
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


@import "settings";
^
      Invalid CSS after "": expected 1 selector or at-rule, was "var content = requi"
      in PATH_TO\assets\styles\main.scss (line 1, column 1)

File: assets\styles\main.scss
```

**Comment by Cry0nicS** [comment]
As it was mentioned by @jonhaddow in #9 , the reason these errors happen is, most likely, because this plugin doesn't work together with `gatsby-plugin-sass`.

Uninstall first `gatsby-plugin-sass` (make sure you also remove it from gatsby-config), then proceed with the installation of `gatsby-plugin-scss-typescript` according to the README.

This should do the trick. @Erythros @nayots

**Comment by fgerschau** [comment]
Not working for me either. Only error I get is:

```
3:20 Cannot find module './about.module.scss' or its corresponding type declarations.
```

No type definitions are generated.

**Comment by Erythros** [comment]
@fgerschau do you have a git repo? Can you share your package.json?

**Comment by Cry0nicS** [comment]
@fgerschau can you share your package.json?

**Comment by fgerschau** [comment]
Sure:

```
{
  "dependencies": {
    "@mdx-js/mdx": "^1.5.8",
    "@mdx-js/react": "^1.5.8",
    "gatsby": "^2.19.12",
    "gatsby-image": "^2.4.6",
    "gatsby-plugin-anchor-links": "^1.1.1",
    "gatsby-plugin-catch-links": "^2.1.25",
    "gatsby-plugin-feed-mdx": "^1.0.1",
    "gatsby-plugin-google-analytics": "^2.1.35",
    "gatsby-plugin-lodash": "^3.1.20",
    "gatsby-plugin-manifest": "^2.2.41",
    "gatsby-plugin-mdx": "^1.1.8",
    "gatsby-plugin-nprogress": "^2.1.19",
    "gatsby-plugin-react-helmet": "^3.1.22",
    "gatsby-plugin-remove-serviceworker": "^1.0.0",
    "gatsby-plugin-sharp": "^2.4.5",
    "gatsby-plugin-sitemap": "^2.2.27",
    "gatsby-plugin-twitter": "^2.1.19",
    "gatsby-remark-autolink-headers": "^2.1.24",
    "gatsby-remark-copy-linked-files": "^2.1.37",
    "gatsby-remark-images": "^3.1.44",
    "gatsby-remark-prismjs": "^3.3.31",
    "gatsby-remark-relative-images": "^0.2.3",
    "gatsby-remark-responsive-iframe": "^2.2.32",
    "gatsby-source-filesystem": "^2.1.48",
    "gatsby-transformer-sharp": "^2.3.14",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "prismjs": "^1.19.0",
    "react": "^16.10.1",
    "react-disqus-comments": "^1.4.0",
    "react-dom": "^16.10.1",
    "react-helmet": "^5.2.1",
    "react-share": "^4.0.1",
    "typescript": "^3.9.5",
    "url-join": "^4.0.0"
  },
  "devDependencies": {
    "@typescript-eslint/parser": "^3.2.0",
    "cli-glob": "^0.1.0",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.10.0",
    "eslint-plugin-filenames": "^1.3.2",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-react": "^7.18.2",
    "eslint-plugin-react-hooks": "^4.0.4",
    "eslint_d": "^9.0.0",
    "gatsby-plugin-force-trailing-slashes": "^1.0.4",
    "gatsby-plugin-scss-typescript": "^4.0.12",
    "gatsby-plugin-ts": "^2.7.1",
    "gatsby-remark-table-of-contents": "^0.0.9",
    "gh-pages": "^2.2.0",
    "node-sass": "^4.14.1",
    "prettier": "^1.17.0",
    "remark-cli": "^7.0.0",
    "remark-preset-lint-recommended": "^3.0.2",
    "stylelint": "^13.0.0",
    "stylelint-config-sass-guidelines": "^7.0.0",
    "write-good": "^1.0.1"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "main": "n/a",
  "scripts": {
    "start": "gatsby develop",
    "test": "echo \"no tests\"",
    "deploy": "gatsby build --prefix-paths && gh-pages -b master -d public -r https://$GH_TOKEN@github.com/fgerschau/fgerschau.github.io.git",
    "dev": "npm run develop",
    "serve": "gatsby serve",
    "build": "gatsby build",
    "build:pp": "gatsby build --prefix-paths",
    "build:gh": "npm run clean && npm run build:pp && gh-pages -d public",
    "clean": "rm -rf public && rm -rf .cache",
    "lint:js": "eslint --ext .js,.jsx .",
    "lint:md": "remark content/",
    "write-good": "write-good $(glob 'content/posts/**/*.md')",
    "format:js": "prettier '**/*.{js,jsx}' --write",
    "format:styles": "prettier '**/*.{css,scss}' --write"
  },
  "remarkConfig": {
    "plugins": [
      "remark-preset-lint-recommended"
    ]
  }
}
```

**Comment by fgerschau** [comment]
@Cry0nicS sure

```
  "dependencies": {
    "@mdx-js/mdx": "^1.5.8",
    "@mdx-js/react": "^1.5.8",
    "gatsby": "^2.19.12",
    "gatsby-image": "^2.4.6",
    "gatsby-plugin-anchor-links": "^1.1.1",
    "gatsby-plugin-catch-links": "^2.1.25",
    "gatsby-plugin-feed-mdx": "^1.0.1",
    "gatsby-plugin-google-analytics": "^2.1.35",
    "gatsby-plugin-lodash": "^3.1.20",
    "gatsby-plugin-manifest": "^2.2.41",
    "gatsby-plugin-mdx": "^1.1.8",
    "gatsby-plugin-nprogress": "^2.1.19",
    "gatsby-plugin-react-helmet": "^3.1.22",
    "gatsby-plugin-remove-serviceworker": "^1.0.0",
    "gatsby-plugin-sharp": "^2.4.5",
    "gatsby-plugin-sitemap": "^2.2.27",
    "gatsby-plugin-twitter": "^2.1.19",
    "gatsby-remark-autolink-headers": "^2.1.24",
    "gatsby-remark-copy-linked-files": "^2.1.37",
    "gatsby-remark-images": "^3.1.44",
    "gatsby-remark-prismjs": "^3.3.31",
    "gatsby-remark-relative-images": "^0.2.3",
    "gatsby-remark-responsive-iframe": "^2.2.32",
    "gatsby-source-filesystem": "^2.1.48",
    "gatsby-transformer-sharp": "^2.3.14",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "prismjs": "^1.19.0",
    "react": "^16.10.1",
    "react-disqus-comments": "^1.4.0",
    "react-dom": "^16.10.1",
    "react-helmet": "^5.2.1",
    "react-share": "^4.0.1",
    "typescript": "^3.9.5",
    "url-join": "^4.0.0"
  },
  "devDependencies": {
    "@typescript-eslint/parser": "^3.2.0",
    "cli-glob": "^0.1.0",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.10.0",
    "eslint-plugin-filenames": "^1.3.2",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-react": "^7.18.2",
    "eslint-plugin-react-hooks": "^4.0.4",
    "eslint_d": "^9.0.0",
    "gatsby-plugin-force-trailing-slashes": "^1.0.4",
    "gatsby-plugin-scss-typescript": "^4.0.12",
    "gatsby-plugin-ts": "^2.7.1",
    "gatsby-remark-table-of-contents": "^0.0.9",
    "gh-pages": "^2.2.0",
    "node-sass": "^4.14.1",
    "prettier": "^1.17.0",
    "remark-cli": "^7.0.0",
    "remark-preset-lint-recommended": "^3.0.2",
    "stylelint": "^13.0.0",
    "stylelint-config-sass-guidelines": "^7.0.0",
    "write-good": "^1.0.1"
  },
```

**Comment by Debens** [comment]
Issues like these are usually repository specific, where some config is misaligned or an incorrect assumption has been made, and are going to be hard to debug through a github issue chain.

I'd added a short [FAQs section](https://github.com/Debens/gatsby-plugin-scss-typescript#im-not-seeing-any-files-being-created) to the README that might be helpful in your case, it might not, but worth a quick check to align on some of the assumptions.

The next steps, if that didn't resolve the issue for you would be to share your repo if its public, and if that's not feasible, create an example repo that can reliably reproduce the issue.

**Comment by fgerschau** [comment]
@Debens thanks! I just found out why it didn't work: I was using `gatsby-plugin-ts` instead of `gatsby-plugin-typescript`. I prefer the first package because it actually uses the TypeScript compiler.

**Comment by Debens** [comment]
@fgerschau nice, glad you found the issue!

I'm going to close off this issue as I think this subject is too broad to be allowed to live. If you disagree with this please open another issue with as many details as you possibly can and I'll be happy to look into it for you! preferably with a link to an example repo.

@Cry0nicS, thank you for picking up the slack, you're an angel and have been super helpful, the world needs more people like you!
