### ISSUE TITLE
Build broken after adding plugin

### ISSUE THREAD

**Issue by JakubKoralewski** [Debens/gatsby-plugin-scss-typescript#9]
```
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


@tailwind base;
^
      Invalid CSS after "": expected 1 selector or at-rule, was "var content = requi"
      in D:\src\css\index.scss (line 1, column 1)

File: src\css\index.scss


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


ul {
^
      Invalid CSS after "": expected 1 selector or at-rule, was "var content = requi"
      in D:\src\components\Nav\nav.module.scss (lin
e 1, column 1)

File: src\components\Nav\nav.module.scss
```

```json
//package.json
    "gatsby-plugin-scss-typescript": "^4.0.10",
    "node-sass": "^4.13.1",
```

**Comment by Debens** [comment]
Can you provide an example repo to reproduce the issue?

**Comment by jonhaddow** [comment]
I've replicated the issue in this example repo - https://github.com/jonhaddow/gatsby-plugin-scss-typescript-issue-9

**Comment by jonhaddow** [comment]
This is caused by `gatsby-plugin-sass` being included in the gatsby-config.js file. When removed, this plugin works. 

It wasn't clear (at least to me) that this plugin is a replacement for `gatsby-plugin-sass` plugin. Perhaps it needs to be clarified in the readme?

**Comment by Debens** [comment]
@jonhaddow - many thanks for investigating. I'll add a preamble about the plugin being a drop in.
